allowBuilds:
  sharp: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.4
  vite-plus: 0.2.4
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
minimumReleaseAgeExclude:
  - "@module-federation/bridge-react-webpack-plugin@2.7.0"
  - "@module-federation/cli@2.7.0"
  - "@module-federation/dts-plugin@2.7.0"
  - "@module-federation/enhanced@2.7.0"
  - "@module-federation/error-codes@2.7.0"
  - "@module-federation/inject-external-runtime-core-plugin@2.7.0"
  - "@module-federation/managers@2.7.0"
  - "@module-federation/manifest@2.7.0"
  - "@module-federation/rspack@2.7.0"
  - "@module-federation/runtime-core@2.7.0"
  - "@module-federation/runtime-tools@2.7.0"
  - "@module-federation/runtime@2.7.0"
  - "@module-federation/sdk@2.7.0"
  - "@module-federation/third-party-dts-extractor@2.7.0"
  - "@module-federation/webpack-bundler-runtime@2.7.0"
